version: "1.1"
pipeline:
  name: bodywork-jupyter-pipeline-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: stage_1_train_model >> stage_2_score_data
stages:
  stage_1_train_model:
    executable_module_path: train_model.ipynb
    requirements:
      - boto3==1.24.13
      - pandas==1.4.2
      - joblib==1.1.0
      - scikit-learn==1.1.1
    cpu_request: 0.5
    memory_request_mb: 250
    batch:
      max_completion_time_seconds: 120
      retries: 1
  stage_2_score_data:
    executable_module_path: score_data.ipynb
    requirements:
      - boto3==1.24.13
      - numpy==1.22.4
      - pandas==1.4.2
      - joblib==1.1.0
      - scikit-learn==1.1.1
    cpu_request: 0.5
    memory_request_mb: 250
    batch:
      max_completion_time_seconds: 120
      retries: 1
logging:
  log_level: INFO
