version: "1.0"
project:
  name: bodywork-jupyter-pipeline-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: stage_1_train_model >> stage_2_score_data
stages:
  stage_1_train_model:
    executable_module_path: stage_1_train_model/nb_runner.py
    requirements:
      - boto3==1.16.15
      - joblib==0.17.0
      - jupyter==1.0.0
      - nbconvert==6.0.7
      - pandas==1.1.4
      - scikit-learn==0.23.2
    cpu_request: 0.5
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
  stage_2_score_data:
    executable_module_path: stage_2_score_data/nb_runner.py
    requirements:
      - boto3==1.16.15
      - joblib==0.17.0
      - jupyter==1.0.0
      - nbconvert==6.0.7
      - numpy==1.19.4
      - pandas==1.1.4
      - scikit-learn==0.23.2
    cpu_request: 0.5
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
logging:
  log_level: INFO
