version: "1.1"
pipeline:
  name: bodywork-jupyter-pipeline-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: stage_1_train_model >> stage_2_score_data
stages:
  stage_1_train_model:
    executable_module_path: train_model.ipynb
    requirements:
      - boto3==1.16.15
      - joblib==0.17.0
      - jupyter==1.0.0
      - nbconvert==6.0.7
      - pandas==1.1.4
      - scikit-learn==0.23.2
    cpu_request: 0.5
    memory_request_mb: 250
    batch:
      max_completion_time_seconds: 120
      retries: 1
  stage_2_score_data:
    executable_module_path: score_data.ipynb
    requirements:
      - boto3==1.16.15
      - joblib==0.17.0
      - jupyter==1.0.0
      - nbconvert==6.0.7
      - numpy==1.19.4
      - pandas==1.1.4
      - scikit-learn==0.23.2
    cpu_request: 0.5
    memory_request_mb: 250
    batch:
      max_completion_time_seconds: 120
      retries: 1
logging:
  log_level: INFO
